# Generated by Django 4.2.3 on 2023-07-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SourisModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                (
                    "complete_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("mouse_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tumor_volume",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cbl", models.CharField(blank=True, max_length=5, null=True)),
                ("h_rate", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.CharField(blank=True, max_length=255, null=True)),
                ("old_cage", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
